# Generated by Django 4.2.23 on 2025-07-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineevent',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
