# Generated by Django 4.2.23 on 2025-09-06 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_exampreparation_document_exam_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('reading', 'Reading Material'), ('questions', 'Previous Year Questions')], default='reading', max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_analyses', to='documents.exampreparation')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='related_analyses', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
