# Generated by Django 4.2.23 on 2025-07-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_exampreparation_document_exam_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineevent',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routineevent',
            name='question_pattern',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='routineevent',
            name='syllabus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routineevent',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
