# Generated by Django 4.2.23 on 2025-09-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_category_questionanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanalysis',
            name='full_analysis_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanalysis',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanalysis',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
